{% set name = "PDielec" %}
{% set version = "6.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc0f12b0b798e509dc595b00d7c7cba210a4c73afca90c7983a031d1656a3c3e

build:
  noarch: python
  number: 0
  entry_points:
    - preader=PDielec.preader:main
    - p2cif=PDielec.p2cif:main
    - pdcompare=PDielec.pdcompare:main
    - pdgui=PDielec.pdgui:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib-base
    - numpy
    - scipy
    - pyqt
    - pyopengl
    - pymiescatt
    - xlsxwriter
    - pyyaml
    - openpyxl
    - termcolor
    - imageio
    - imageio-ffmpeg
    - ffmpeg
    - requests
    - beautifulsoup4
    - bleach
    - docutils
    - psutil
    - pygments

test:
  imports:
    - PDielec
  commands:
    - pip check
    - preader --help
    - p2cif --help
  requires:
    - pip

about:
  home: https://github.com/JohnKendrick/PDielec
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PDielec package for the calculation of THz and infrared spectra
  doc_url: https://johnkendrick.github.io/PDielec
  dev_url: https://github.com/JohnKendrick/PDielec

extra:
  recipe-maintainers:
    - JohnKendrick
