{% set name = "PDielec" %}
{% set version = "6.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8aa9c8a6c2f20fb8a5462b92040841f5257ea95ec199ec1168feeb982c5630af

build:
  noarch: python
  number: 0
  entry_points:
    - preader=PDielec.preader:main
    - pdgui=PDielec.pdgui:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - matplotlib-base
    - numpy
    - scipy
    - pyqt
    - pyopengl
    - pymiescatt
    - xlsxwriter
    - pyyaml
    - openpyxl
    - termcolor
    - imageio

test:
  imports:
    - PDielec
  commands:
    - pip check
    - preader --help
  requires:
    - pip

about:
  home: https://github.com/JohnKendrick/PDielec
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PDielec package for the calculation of THz and infrared spectra
  doc_url: https://johnkendrick.github.io/PDielec
  dev_url: https://github.com/JohnKendrick/PDielec

extra:
  recipe-maintainers:
    - JohnKendrick
