{% set name = "pdielec" %}
{% set version = "9.0.1" %}
{% set python_min = "3.7" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46b2ec6e5c06f7242333a4363ee861eba0787b4be507a0bd7ec4412e45c503f5

build:
  noarch: python
  number: 0
  entry_points:
    - preader=PDielec.preader:main
    - p2cif=PDielec.p2cif:main
    - pickled_reader=PDielec.pickled_reader:main
    - pdcompare=PDielec.pdcompare:main
    - pdgui=PDielec.pdgui:main
    - pdmake=PDielec.pdmake:main
    - vibanalysis=PDielec.vibanalysis:main
    - phonopy-pdielec-born=PDielec.phonopy_pdielec_born:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - blas =*=openblas
    - matplotlib-base
    - numpy
    - scipy
    - scikit-learn
    - pyqt
    - qtpy
    - pyopengl
    - xlsxwriter
    - pyyaml
    - openpyxl
    - termcolor
    - imageio
    - imageio-ffmpeg
    - ffmpeg
    - requests
    - beautifulsoup4
    - bleach
    - docutils
    - psutil
    - pygments
    - dill
    - spglib

test:
  imports:
    - PDielec
  commands:
    - preader --help
    - p2cif --help
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/JohnKendrick/PDielec
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: PDielec package for the calculation of THz and infrared spectra
  doc_url: https://johnkendrick.github.io/PDielec
  dev_url: https://github.com/JohnKendrick/PDielec

extra:
  recipe-maintainers:
    - JohnKendrick
    - ADBurnett
